# Generated by Django 4.2.1 on 2023-05-17 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('photo_book', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('pages', models.IntegerField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rental_periud', models.IntegerField(blank=True, max_length=20, null=True)),
                ('total_rental', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('avalible', 'avalible'), ('sold', 'sold'), ('rental', 'rental')], max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms_app.category')),
            ],
        ),
    ]
